In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

In [3]:
sizes = np.random.randint(500, 35000, 100)

In [4]:
size

array([29320,  9364, 32064, 10590, 28172, 32204, 34607, 21272, 22875,
         809, 16522, 34396, 34874, 18400, 28049, 26253, 21868, 14502,
        8711,  9366, 28026, 16604, 27873, 20228,  1833, 15175,  1427,
       29014,  3609, 17718, 30473, 21340, 13423, 30347,  7392, 28396,
       24750, 17134, 23459, 12642, 14999,  5845, 31659,  9384, 26034,
       13397, 33270, 17386, 29266, 30769, 28010, 13501, 31814, 32299,
       10631, 12300, 25407, 30397, 16375, 15226, 22889,  1421,  4743,
       26026, 31106,  6036,  2463, 26274, 34243, 20213, 32208, 26030,
       30307, 15416, 10777, 34349, 23172, 30113, 29801, 33176, 15039,
       10173, 32368, 23074, 12448, 30035, 25212, 10455, 25236, 11211,
        6256, 34019, 26185, 11304, 33306, 32858, 17363, 22942,   839,
       33204])

In [5]:
bedrooms = np.random.randint(1,6,100)

In [6]:
len(bedrooms)

100

In [7]:
prices = (sizes * 0.3) + (bedrooms * 50) + np.random.randint(-200, 200, 100)

In [8]:
prices

array([ 5267.6,  6358.8,   788.8,  9131.8,  9783.5,  6687.3,  4330.8,
        7604.6,  5074.1,  6410.2,  1039.3,  7879.7,  8882.6,  2911.4,
        2000.6, 10055.6,  1423.4, 10373.4,  5161.3,  9352.6,  6381.1,
        7742.9,  9875.3,  7558.5,   993.8,  7678.1,  6210.4,  3713.9,
        2428.8,  4511.7,  2617.5, 10248.5,   987. ,  3171.7,  5181.3,
        7057. ,  6659.9,  9340.4, 10834. ,  2269.4, 10657.1,  9709.2,
        7541.8,  3705.2,  8035. ,  4903. ,  5903.7,  4762.8,  1401.9,
        7616.6,  2662.4, 10014.4,  1842.2,  8865.5,  9977.1,  4593.9,
        3322.8,  7897.1, 10236.8,  1171. ,   714.2,  9098.1,  2413.5,
        7407.5,  4152.7, 10244. ,  6650.5, 10229. ,  1261. ,  8606.6,
        3194.1,  6525.7,  5033.5,  7098.3,  7444.4,  8549.8,  7753.6,
        5397.2,  5646.7,   743.8,  9234.4,  4320.6,  4459.9,  4533.5,
        6964.6,  5730.7,  4945. ,  6360.1,  9546.2,  1328.7,  6229.2,
        4710.1,  3765.8, 10322.4,  4659.7,  9302.1,  3757.3,  3553.9,
        7398. ,  635

In [9]:
data = pd.DataFrame({
    "size_sqft" : sizes,
    "bedrooms" : bedrooms,
    "price" : prices
})

In [10]:
data.head()

size_sqft  bedrooms   price
0      17162         1  5267.6
1      21386         2  6358.8
2       2046         2   788.8
3      30236         3  9131.8
4      32235         3  9783.5

In [11]:
X = data[["size_sqft","bedrooms"]]

In [12]:
y = data["price"]

In [13]:
model = LinearRegression()

In [14]:
model.fit(X,y)

LinearRegression()

In [15]:
sample_X = np.array([[2000,3], [1500,2]])

In [16]:
model.predict(sample_X)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([766.6823134 , 566.01153597])

In [17]:
with open("house_price_model.pkl","wb") as f:
    pickle.dump(model, f)